databases:
  - name: postgres
    ipAllowList: []
    plan: paid
    
services: 
  - type: web
    name: rails
    plan: paid
    env: ruby
    buildCommand: "./bin/render-build.sh" 
    startCommand: bundle exec rails s
    envVars: 
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: paid
    maxmemoryPolicy: noeviction